collections:
  shields:
    output: true
    permalink: /details/:name/
  shieldcategories:
    output: true
    permalink: /category/:name-shields/

defaults:
  - scope:
      path: ""
      type: shields
    values:
      layout: shield
  - scope:
      path: ""
      type: shieldcategories
    values:
      layout: shieldcategory