collections:
  shield:
    output: true
    permalink: /shield/:name/
  shields:
    output: true
    permalink: /shields/:name/

defaults:
  - scope:
      path: ""
      type: shield
    values:
      layout: shield
  - scope:
      path: ""
      type: shields
    values:
      layout: shields